### ISSUE TITLE
There isn't any TODO list nor anything similar to help new contributors knowing where to start

### ISSUE THREAD

**Issue by castarco** [10gen-labs/mongo-php-library-prototype#24]
Hi,

there isn't any TODO list nor anything similar (like using this 'bugtracker' with specific tags) to help new contributors knowing where to start or which features aren't developed yet.

I'll try to help if there are a comprehensible TODO list, but I haven't the time to explore the entire mongo PHP prototypes source code because business is business. First user stories, (sadly for me) in last place the portability and my dreamed port to HHVM.

**Comment by bjori** [comment]
TODO lists become stale very fast as they require to much extra book keeping.
We use JIRA for our ticket management, see the [PHPLIB](https://jira.mongodb.org/issues/?jql=project%20%3D%20PHPLIB%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20priority%20DESC) project on https://jira.mongodb.org.

The current focus has been to release the new base extension, [phongo](https://github.com/10gen-labs/mongo-php-driver-prototype), which this library is wrapping.

phongo just this week [shipped 1.0.0-alpha](https://github.com/10gen-labs/mongo-php-driver-prototype/releases) (the release notes will be posted ASAP), so the focus will now move to this library to catch up on all the improvements.

I think the biggest contribution we could imagine at this point is to test this out, play around, and contribute opinions and experience.
The extension is pretty much completed at this point (pending handful of issues in the [library it wraps, mongoc](https://github.com/mongodb/mongo-c-driver)) so could use some banging.
The PHPLIB needs slight updating (in particular a release) to be compatible with the new alpha, after that it already has the majority of the CRUD things implemented, but needs more experience and game time.

**Comment by castarco** [comment]
Ok, thank you @bjori for your explanation.
